### ISSUE TITLE
Change using db

### ISSUE THREAD

**Issue by kairatomurbek2** [jazzband/django-auditlog#299] opened 2021-04-16 10:03 UTC

**Comment by kairatomurbek2** [comment] 2021-04-16 10:04
Let's say I have a main database, and I need the auditlog to have its own database

**Comment by kairatomurbek2** [comment] 2021-04-16 10:05
Let's say I have a main database, and I need the auditlog to have its own database

**Comment by Linkid** [comment] 2022-01-12 10:01
Hi ! Thanks for this issue !
This is a duplicate of #321, which has a link to the doc. So, I'm closing this issue.

**Closed by Linkid** 2022-01-12 10:01 UTC
Labels: duplicate, enhancement
