### ISSUE TITLE
Changes logged for JSON-field aren't valid JSON

### ISSUE THREAD

**Issue by lukaszett** [jazzband/django-auditlog#476] opened 2022-12-15 19:25 UTC
Hello everyone,

suppose I have the following model:
```
from django.db import models

from auditlog.registry import auditlog

class Foo(models.Model):
    bar = models.JSONField()


auditlog.register(Foo)
```

Now I create a new instance and check for the last LogEntry:
```
Foo.objects.create(bar={"baz":1})
entry = LogEntry.objects.latest()
bar_changes = entry.changes_dict.get("bar")
new_bar = bar_changes[1]
print(new_bar)
```

This outputs:
```
{'baz': 1}
```

I would expect the log entries for JsonFields to be a valid string to feed into `json.loads` however, the double quotes around the keys get converted into single quotes which is not allowed for json. I did some digging into where this conversion happens but I didn't really come to a conclusion.

Is this the desired behaviour or is it a bug?

**Comment by hramezani** [comment] 2022-12-16 14:13
Hello @lukaszett,

Thanks for reporting this issue.

I think it's because we don't `dumps` the `JSONField` value to when we make the diff.

https://github.com/jazzband/django-auditlog/blob/971a4f42f8ce0ee8d376c6567199e1d223571c08/auditlog/diff.py#L75

Probably it can be fixed by changing it like

```python
value = json.dumps(field.to_python(getattr(obj, field.name, None)))
```

Would you like to work on it @lukaszett ?

**Comment by CleitonDeLima** [comment] 2022-12-28 20:43
> Probably it can be fixed by changing it like

I think you also need to consider that the get value of an already saved json field is a dict and not a json string.

**Comment by CleitonDeLima** [comment] 2022-12-29 11:25
can i do a PR of this @hramezani?

**Comment by hramezani** [comment] 2022-12-29 11:41
@CleitonDeLima sure!
But first of all try to reproduce the problem on master. I guess the problem might be fixed by the breaking chane PR that got merged yesterday.

**Closed** 2022-12-30 07:28 UTC
Labels: bug, good first issue
