### ISSUE TITLE
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding' 

### ISSUE THREAD

**Issue by sant527** [jazzband/django-auditlog#311] opened 2021-07-08 11:25 UTC
I use

```
django-auditlog 0.4.7
$ python --version
Python 3.7.3
$ django-admin --version
3.2.3
```

I am trying to do

```
python manage.py migrate
```

I get 

```
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding' (/projectpth/.venv/lib/python3.7/site-packages/django/utils/encoding.py)
```

**Comment by faustovexels** [comment] 2021-07-31 19:26
Same here

**Comment by klemmari1** [comment] 2021-08-11 12:05
I would rather just install a version of the original pip package that supports Python 3.0:

`pip install django-auditlog==1.0a1`

**Comment by Linkid** [comment] 2022-01-04 09:51
Hi. This is a duplicate of #265. Thanks anyway to have reported it :).

**Closed by Linkid** 2022-01-04 09:51 UTC
