### ISSUE TITLE
Custom signal post_log is triggered even when LogEntry is not created

### ISSUE THREAD

**Issue by rejuls** [jazzband/django-auditlog#536] opened 2023-06-20 12:25 UTC
From https://github.com/jazzband/django-auditlog/blob/master/auditlog/receivers.py#L99

```
    try:
        changes = model_instance_diff(
            diff_old, diff_new, fields_to_check=fields_to_check
        )

        if force_log or changes:
            LogEntry.objects.log_create(
                instance,
                action=action,
                changes=changes,
                force_log=force_log,
            )
    except BaseException as e:
        error = e
    finally:
        post_log.send(
            sender,
            instance=instance,
            action=action,
            error=error,
            pre_log_results=pre_log_results,
        )
        if error:
            raise error
```
When `changes` is None implying that the model was saved with no changes,  LogEntry object is not created, but the post_log signal is still being send in the `finally` block which shouldnt happen.

To reproduce the issue:
1. Set any registered model with a receiver for the post_log signal to print a log
2. Save an object without any changes

I am using the last master commit for this.

Another issue here is that the "Custom Signals" feature is not released yet but is part of the public documentation already - https://django-auditlog.readthedocs.io/en/latest/internals.html#custom-signals

**Comment by hramezani** [comment] 2023-06-21 14:35
Thanks @rejuls for reporting this bug.

Would you like to open a PR and provide a fix + test for this issue?

> Another issue here is that the "Custom Signals" feature is not released yet but is part of the public documentation already - https://django-auditlog.readthedocs.io/en/latest/internals.html#custom-signals

Yes, unfortunately. we need to somehow fix the problem. But I don't have enough time nowadays to take a look at this.

**Comment by hramezani** [comment] 2023-06-21 14:35
cc @aqeelat

**Comment by aqeelat** [comment] 2023-06-24 12:32
Great catch, @rejuls!

I guess these are two different issues.
We should discuss the signal issue here, but we need to open another issue for the docs one.

The intended behavior was to fire the signal even when there is an exception. I think one way to solve this is to pass the changes to the signal so that the receiver can return early if the changes were None.

**Comment by aqeelat** [comment] 2023-06-24 12:34
Maybe we can pass `has_changes=bool(changes), force_log=force_log` to the signal.

what do you think @hramezani?

**Comment by hramezani** [comment] 2023-06-24 16:03
@aqeelat `has_changes` makes more sense to me.

**Comment by rejuls** [comment] 2023-06-26 13:20
Understood, when is the next release with this change slated to happen? I will make the fix for this if I can get time by then. Will also open a separate issue for the documentation problem.

**Comment by aabanaag** [comment] 2023-08-25 06:23
Hello, sorry to hijack the conversation, but just wanted to ask if pre_log signals exist on the 2.3.0 release.

**Comment by hramezani** [comment] 2023-08-25 07:02
Hey @aabanaag, no, It will be available in V3. we are preparing a beta release for V3 and it will be available soon

**Comment by hramezani** [comment] 2023-08-31 07:37
@aqeelat Did we address this issue? I think we still haven't fix this. right?

**Comment by aqeelat** [comment] 2023-08-31 09:50
@hramezani I don't think we decided if this is an actual issue.

**Comment by hramezani** [comment] 2023-08-31 09:58
@aqeelat, Actually, it is an improvement to let the signal receiver know about the change.
I think your suggestion about passing `has_changes` to the signal receiver is good and we can include it.

**Comment by aqeelat** [comment] 2023-09-05 11:35
@hramezani I'm currently looking at the code.

Since `model_instance_diff` is getting called inside the try statement, we can't guarantee that changes will have a value in the finally statement (if the function raises an exception). Which means that we could've sent `has_changes=False` when it did have changes but an exception was thrown.

My suggestion is to use a boolean called log_created:
```python
        if force_log or changes:
            LogEntry.objects.log_create(
                instance,
                action=action,
                changes=changes,
                force_log=force_log,
            )
            log_created = True
```
But there are two options on what to do with it:
1. send it to the post_log signal and let the receiver handle it as they wish.
2. only fire the signal if `log_created or error`. This will solve OP's issue but the receiver will have to no way of knowing if it was fired because of `force_log` or because of `changes`. 

Stepping back a bit: do we have documentation on why `model_instance_diff` might raise an exception?

**Comment by aqeelat** [comment] 2023-09-05 11:35
Sorry I closed it by mistake.

**Comment by hramezani** [comment] 2023-09-05 13:22
@aqeelat I would prefer `option 1` to let the receiver handle it.
I think we still can send other params like `force_log` or `changes` if they are helping.

**Comment by aqeelat** [comment] 2023-09-06 10:50
@hramezani yeah but is it helpful to always fire a signal even if the log was not created? I think the idea here is to make something similar to `post_save.connect(my_method, sender=LogEntry)` but with error handling.

**Comment by hramezani** [comment] 2023-09-06 11:02
> @hramezani yeah but is it helpful to always fire a signal even if the log was not created? I think the idea here is to make something similar to `post_save.connect(my_method, sender=LogEntry)` but with error handling.

agree,probably we don't need to fire a signal in this case

**Closed** 2023-09-07 12:28 UTC
Labels: bug
