### ISSUE TITLE
v1.0a1 AttributeError on changes_display_dict for ManyToOne relation

### ISSUE THREAD

**Issue by gsimore** [jazzband/django-auditlog#293] opened 2021-02-01 18:49 UTC
When accessing the property `changes_display_dict` on a LogEntry with a ManyToOneRelation, I get the following error:
(running with Django 3.1 and Python 3.8.5, and version 1.0a1 of auditlog.)

```
AttributeError                            Traceback (most recent call last)
<ipython-input-3-77e970a5d758> in <module>
      1 for h in history:
----> 2     print(h.changes_display_dict)
      3 

~/.virtualenvs/dashboard/lib/python3.8/site-packages/auditlog/models.py in changes_display_dict(self)
    259             # handle choices fields and Postgres ArrayField to get human readable version
    260             choices_dict = None
--> 261             if getattr(field, 'choices') and len(field.choices) > 0:
    262                 choices_dict = dict(field.choices)
    263             if hasattr(field, 'base_field') and isinstance(field.base_field, Field) and getattr(field.base_field, 'choices') and len(field.base_field.choices) > 0:

AttributeError: 'ManyToOneRel' object has no attribute 'choices'
```

**Comment by Flor1an-dev** [comment] 2021-03-30 09:18
This looks like a duplicate of #273

**Comment by nanuxbe** [comment] 2021-10-01 12:25
I also have the same issue. #273 was closed.
Of all proposed fixes, the one by @viktor2097 is the only one that works for me.

Other than the fact 
> There's not a case where this doesn't exist, unless you go so far as to consider some crazy monkey patching or other questionable practices, in which I suspect many more things will break as well. choices is set in __init__()`` of django.db.models.fields.Field`. ManyToMany fields are not supported. That said, doesn't seem like this hurts anything.

Is there anything blocking this Pull Request? I don't really understand why it got closed?

**Closed** 2021-10-01 12:48 UTC

**Comment by tudoanh** [comment] 2022-05-31 15:34
I'm having this problem too

**Comment by hramezani** [comment] 2022-06-09 07:23
> I'm having this problem too

@tudoanh 
Could you please give me a small example that reproduces the problem?
